" initialize our vimrc loader
execute 'source ' . $RCDIR . '/configs/vim/init.vim'

" load in our various script files to construct our particular set of
" settings.
call g:myVim.LoadScript('directory-vimrc')
call g:myVim.LoadScript('projects')
call g:myVim.LoadScript('mappings')
call g:myVim.LoadScript('settings')
call g:myVim.LoadScript('filetypes')
call g:myVim.LoadScript('vundle')

" add a DiffWithSaved() command to see what changes we haven't saved yet
    function! s:DiffWithSaved()
        let filetype=&ft
        diffthis
        vnew | r # | normal! 1Gdd
        diffthis
        exe "setlocal bt=nofile bh=wipe nobl noswf ro ft=" . filetype
    endfunction
    com! DiffSaved call s:DiffWithSaved()
