# unfortunately, according to http://mywiki.wooledge.org/BashFAQ/028, there's
# no way to determine what the currently-executing filename is consistently,
# so this is code-copied to both zshrc and bashrc. Sadface.
if [ -z $RCDIR ]; then
    [ -r "$HOME/.rcdir" ] && RCDIR=$(cat $HOME/.rcdir)
    [ -z $RCDIR ]         && RCDIR=$HOME/.rc

    [ -d $RCDIR ] || echo "WARNING: RCDIR $RCDIR is not a directory" >&2
fi
export RCDIR

# setup our environment
source "$RCDIR/configs/shell/environment.sh"
source "$RCDIR/configs/shell/functions.sh"
source "$RCDIR/configs/shell/aliases.sh"
source "$RCDIR/configs/shell/autoupdate.sh"

# zsh-specific configuration from here on out
HISTFILE="$HOME/.history/zsh"

export ZSH_CUSTOM="$RCDIR/configs/shell/zsh_custom"

# oh-my-zsh
ZSH=$HOME/.oh-my-zsh
ZSH_THEME=sammy-modified
plugins=()

# DISABLE_LS_COLORS prevents oh-my-zsh from overriding our ls alias
# DISABLE_UPDATE_PROMPT makes zsh auto-update without asking
DISABLE_LS_COLORS=true DISABLE_UPDATE_PROMPT=true \
    source $ZSH/oh-my-zsh.sh
