# unfortunately, according to http://mywiki.wooledge.org/BashFAQ/028, there's
# no way to determine what the currently-executing filename is consistently,
# so this is code-copied to both zshrc and bashrc. Sadface.
if [ -z $RCDIR ]; then
    [ -r "$HOME/.rcdir" ] && RCDIR=$(cat $HOME/.rcdir)
    [ -z $RCDIR ]         && RCDIR=$HOME/.rc

    [ -d $RCDIR ] || echo "WARNING: RCDIR $RCDIR is not a directory" >&2
fi
export RCDIR

# setup our environment
source "$RCDIR/shell/environment.sh"
source "$RCDIR/shell/functions.sh"
source "$RCDIR/shell/aliases.sh"

# zsh-specific configuration from here on out
HISTFILE="$HOME/.history/zsh"

# oh-my-zsh
ZSH=$HOME/.oh-my-zsh
ZSH_THEME=cloud
plugins=()

# DISABLE_LS_COLORS prevents oh-my-zsh from overriding our ls alias
DISABLE_LS_COLORS=true \
    source $ZSH/oh-my-zsh.sh
